/*
 * IDENTIFICATION:
 * stub generated Fri Apr 16 00:00:00 2021
 * with a MiG generated by bootstrap_cmds-116
 * OPTIONS:
 */

/* clang-format off */

/* Module bootstrap */

#define	__MIG_check__Request__bootstrap_subsystem__ 1

#include <string.h>
#include <mach/ndr.h>
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/message.h>
#include <mach/mig_errors.h>
#include <mach/port.h>
	
/* BEGIN VOUCHER CODE */

#ifndef KERNEL
#if defined(__has_include)
#if __has_include(<mach/mig_voucher_support.h>)
#ifndef USING_VOUCHERS
#define USING_VOUCHERS
#endif
#ifndef __VOUCHER_FORWARD_TYPE_DECLS__
#define __VOUCHER_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif // __VOUCHER_FORWARD_TYPE_DECLS__
#endif // __has_include(<mach/mach_voucher_types.h>)
#endif // __has_include
#endif // !KERNEL
	
/* END VOUCHER CODE */

	
/* BEGIN MIG_STRNCPY_ZEROFILL CODE */

#if defined(__has_include)
#if __has_include(<mach/mig_strncpy_zerofill_support.h>)
#ifndef USING_MIG_STRNCPY_ZEROFILL
#define USING_MIG_STRNCPY_ZEROFILL
#endif
#ifndef __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#define __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern int mig_strncpy_zerofill(char *dest, const char *src, int len) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif /* __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__ */
#endif /* __has_include(<mach/mig_strncpy_zerofill_support.h>) */
#endif /* __has_include */
	
/* END MIG_STRNCPY_ZEROFILL CODE */


#include <mach/std_types.h>
#include <mach/mig.h>
#include "bootstrap_defs.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* typedefs for all requests */

#ifndef __Request__bootstrap_subsystem__defined
#define __Request__bootstrap_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		name_t service_name;
	} __Request__bootstrap_check_in_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t service_port;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		name_t service_name;
	} __Request__bootstrap_register_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		name_t service_name;
	} __Request__bootstrap_look_up_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t service_names;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t service_namesCnt;
	} __Request__bootstrap_look_up_array_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		name_t service_name;
	} __Request__bootstrap_status_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__bootstrap_info_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t requestor_port;
		/* end of the kernel processed data */
	} __Request__bootstrap_subset_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		name_t service_name;
	} __Request__bootstrap_create_service_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
#endif /* !__Request__bootstrap_subsystem__defined */

/* typedefs for all replies */

#ifndef __Reply__bootstrap_subsystem__defined
#define __Reply__bootstrap_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t service_port;
		/* end of the kernel processed data */
	} __Reply__bootstrap_check_in_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__bootstrap_register_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t service_port;
		/* end of the kernel processed data */
	} __Reply__bootstrap_look_up_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_ports_descriptor_t service_ports;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t service_portsCnt;
		boolean_t all_services_known;
	} __Reply__bootstrap_look_up_array_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		boolean_t service_active;
	} __Reply__bootstrap_status_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t service_names;
		mach_msg_ool_descriptor_t server_names;
		mach_msg_ool_descriptor_t service_active;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t service_namesCnt;
		mach_msg_type_number_t server_namesCnt;
		mach_msg_type_number_t service_activeCnt;
	} __Reply__bootstrap_info_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t subset_port;
		/* end of the kernel processed data */
	} __Reply__bootstrap_subset_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t service_port;
		/* end of the kernel processed data */
	} __Reply__bootstrap_create_service_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
#endif /* !__Reply__bootstrap_subsystem__defined */


/* union of all replies */

#ifndef __ReplyUnion__x_bootstrap_subsystem__defined
#define __ReplyUnion__x_bootstrap_subsystem__defined
union __ReplyUnion__x_bootstrap_subsystem {
	__Reply__bootstrap_check_in_t Reply_bootstrap_check_in;
	__Reply__bootstrap_register_t Reply_bootstrap_register;
	__Reply__bootstrap_look_up_t Reply_bootstrap_look_up;
	__Reply__bootstrap_look_up_array_t Reply_bootstrap_look_up_array;
	__Reply__bootstrap_status_t Reply_bootstrap_status;
	__Reply__bootstrap_info_t Reply_bootstrap_info;
	__Reply__bootstrap_subset_t Reply_bootstrap_subset;
	__Reply__bootstrap_create_service_t Reply_bootstrap_create_service;
};
#endif /* __ReplyUnion__x_bootstrap_subsystem__defined */
/* Forward Declarations */


mig_internal novalue _Xbootstrap_check_in
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xbootstrap_register
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xbootstrap_look_up
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xbootstrap_look_up_array
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xbootstrap_status
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xbootstrap_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xbootstrap_subset
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xbootstrap_create_service
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__bootstrap_subsystem__
#if !defined(__MIG_check__Request__bootstrap_check_in_t__defined)
#define __MIG_check__Request__bootstrap_check_in_t__defined

mig_internal kern_return_t __MIG_check__Request__bootstrap_check_in_t(__attribute__((__unused__)) __Request__bootstrap_check_in_t *In0P)
{

	typedef __Request__bootstrap_check_in_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->service_name),  128);
		if (( memchr(In0P->service_name, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__bootstrap_check_in_t__defined) */
#endif /* __MIG_check__Request__bootstrap_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine bootstrap_check_in */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
MIG_SERVER_ROUTINE
kern_return_t bootstrap_check_in
(
	mach_port_t bootstrap_port,
	name_t service_name,
	mach_port_t *service_port
);

/* Routine bootstrap_check_in */
mig_internal novalue _Xbootstrap_check_in
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		name_t service_name;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__bootstrap_check_in_t __Request;
	typedef __Reply__bootstrap_check_in_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__bootstrap_check_in_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__bootstrap_check_in_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t service_portTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		16,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(402, "bootstrap_check_in")
	__BeforeRcvRpc(402, "bootstrap_check_in")

#if	defined(__MIG_check__Request__bootstrap_check_in_t__defined)
	check_result = __MIG_check__Request__bootstrap_check_in_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__bootstrap_check_in_t__defined) */

#if	UseStaticTemplates
	OutP->service_port = service_portTemplate;
#else	/* UseStaticTemplates */
	OutP->service_port.disposition = 16;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->service_port.pad1 = 0;
#endif
	OutP->service_port.pad2 = 0;
	OutP->service_port.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->service_port.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = bootstrap_check_in(In0P->Head.msgh_request_port, In0P->service_name, &OutP->service_port.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(402, "bootstrap_check_in")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__bootstrap_subsystem__
#if !defined(__MIG_check__Request__bootstrap_register_t__defined)
#define __MIG_check__Request__bootstrap_register_t__defined

mig_internal kern_return_t __MIG_check__Request__bootstrap_register_t(__attribute__((__unused__)) __Request__bootstrap_register_t *In0P)
{

	typedef __Request__bootstrap_register_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->service_port.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->service_port.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->service_name),  128);
		if (( memchr(In0P->service_name, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__bootstrap_register_t__defined) */
#endif /* __MIG_check__Request__bootstrap_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine bootstrap_register */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
MIG_SERVER_ROUTINE
kern_return_t bootstrap_register
(
	mach_port_t bootstrap_port,
	name_t service_name,
	mach_port_t service_port
);

/* Routine bootstrap_register */
mig_internal novalue _Xbootstrap_register
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t service_port;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		name_t service_name;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__bootstrap_register_t __Request;
	typedef __Reply__bootstrap_register_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__bootstrap_register_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__bootstrap_register_t__defined */

	__DeclareRcvRpc(403, "bootstrap_register")
	__BeforeRcvRpc(403, "bootstrap_register")

#if	defined(__MIG_check__Request__bootstrap_register_t__defined)
	check_result = __MIG_check__Request__bootstrap_register_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__bootstrap_register_t__defined) */

	OutP->RetCode = bootstrap_register(In0P->Head.msgh_request_port, In0P->service_name, In0P->service_port.name);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(403, "bootstrap_register")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__bootstrap_subsystem__
#if !defined(__MIG_check__Request__bootstrap_look_up_t__defined)
#define __MIG_check__Request__bootstrap_look_up_t__defined

mig_internal kern_return_t __MIG_check__Request__bootstrap_look_up_t(__attribute__((__unused__)) __Request__bootstrap_look_up_t *In0P)
{

	typedef __Request__bootstrap_look_up_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->service_name),  128);
		if (( memchr(In0P->service_name, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__bootstrap_look_up_t__defined) */
#endif /* __MIG_check__Request__bootstrap_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine bootstrap_look_up */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
MIG_SERVER_ROUTINE
kern_return_t bootstrap_look_up
(
	mach_port_t bootstrap_port,
	name_t service_name,
	mach_port_t *service_port
);

/* Routine bootstrap_look_up */
mig_internal novalue _Xbootstrap_look_up
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		name_t service_name;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__bootstrap_look_up_t __Request;
	typedef __Reply__bootstrap_look_up_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__bootstrap_look_up_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__bootstrap_look_up_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t service_portTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(404, "bootstrap_look_up")
	__BeforeRcvRpc(404, "bootstrap_look_up")

#if	defined(__MIG_check__Request__bootstrap_look_up_t__defined)
	check_result = __MIG_check__Request__bootstrap_look_up_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__bootstrap_look_up_t__defined) */

#if	UseStaticTemplates
	OutP->service_port = service_portTemplate;
#else	/* UseStaticTemplates */
	OutP->service_port.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->service_port.pad1 = 0;
#endif
	OutP->service_port.pad2 = 0;
	OutP->service_port.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->service_port.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = bootstrap_look_up(In0P->Head.msgh_request_port, In0P->service_name, &OutP->service_port.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(404, "bootstrap_look_up")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__bootstrap_subsystem__
#if !defined(__MIG_check__Request__bootstrap_look_up_array_t__defined)
#define __MIG_check__Request__bootstrap_look_up_array_t__defined

mig_internal kern_return_t __MIG_check__Request__bootstrap_look_up_array_t(__attribute__((__unused__)) __Request__bootstrap_look_up_array_t *In0P)
{

	typedef __Request__bootstrap_look_up_array_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->service_names.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->service_names.size / 128 != In0P->service_namesCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__bootstrap_look_up_array_t__defined) */
#endif /* __MIG_check__Request__bootstrap_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine bootstrap_look_up_array */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
MIG_SERVER_ROUTINE
kern_return_t bootstrap_look_up_array
(
	mach_port_t bootstrap_port,
	name_array_t service_names,
	mach_msg_type_number_t service_namesCnt,
	mach_port_array_t *service_ports,
	mach_msg_type_number_t *service_portsCnt,
	boolean_t *all_services_known
);

/* Routine bootstrap_look_up_array */
mig_internal novalue _Xbootstrap_look_up_array
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t service_names;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t service_namesCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__bootstrap_look_up_array_t __Request;
	typedef __Reply__bootstrap_look_up_array_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__bootstrap_look_up_array_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__bootstrap_look_up_array_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_ports_descriptor_t service_portsTemplate = {
		/* addr = */		(void *)0,
		/* coun = */		0,
		/* deal = */		FALSE,
		/* copy is meaningful only in overwrite mode */
		/* copy = */		MACH_MSG_PHYSICAL_COPY,
		/* disp = */		19,
		/* type = */		MACH_MSG_OOL_PORTS_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(405, "bootstrap_look_up_array")
	__BeforeRcvRpc(405, "bootstrap_look_up_array")

#if	defined(__MIG_check__Request__bootstrap_look_up_array_t__defined)
	check_result = __MIG_check__Request__bootstrap_look_up_array_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__bootstrap_look_up_array_t__defined) */

#if	UseStaticTemplates
	OutP->service_ports = service_portsTemplate;
#else	/* UseStaticTemplates */
	OutP->service_ports.disposition = 19;
	OutP->service_ports.deallocate =  FALSE;
	OutP->service_ports.type = MACH_MSG_OOL_PORTS_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	OutP->service_portsCnt = 0;

	RetCode = bootstrap_look_up_array(In0P->Head.msgh_request_port, (name_array_t)(In0P->service_names.address), In0P->service_names.size / 128, (mach_port_array_t *)&(OutP->service_ports.address), &OutP->service_portsCnt, &OutP->all_services_known);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->service_ports.count = OutP->service_portsCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(405, "bootstrap_look_up_array")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__bootstrap_subsystem__
#if !defined(__MIG_check__Request__bootstrap_status_t__defined)
#define __MIG_check__Request__bootstrap_status_t__defined

mig_internal kern_return_t __MIG_check__Request__bootstrap_status_t(__attribute__((__unused__)) __Request__bootstrap_status_t *In0P)
{

	typedef __Request__bootstrap_status_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->service_name),  128);
		if (( memchr(In0P->service_name, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__bootstrap_status_t__defined) */
#endif /* __MIG_check__Request__bootstrap_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine bootstrap_status */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
MIG_SERVER_ROUTINE
kern_return_t bootstrap_status
(
	mach_port_t bootstrap_port,
	name_t service_name,
	boolean_t *service_active
);

/* Routine bootstrap_status */
mig_internal novalue _Xbootstrap_status
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		name_t service_name;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__bootstrap_status_t __Request;
	typedef __Reply__bootstrap_status_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__bootstrap_status_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__bootstrap_status_t__defined */

	__DeclareRcvRpc(407, "bootstrap_status")
	__BeforeRcvRpc(407, "bootstrap_status")

#if	defined(__MIG_check__Request__bootstrap_status_t__defined)
	check_result = __MIG_check__Request__bootstrap_status_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__bootstrap_status_t__defined) */

	OutP->RetCode = bootstrap_status(In0P->Head.msgh_request_port, In0P->service_name, &OutP->service_active);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(407, "bootstrap_status")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__bootstrap_subsystem__
#if !defined(__MIG_check__Request__bootstrap_info_t__defined)
#define __MIG_check__Request__bootstrap_info_t__defined

mig_internal kern_return_t __MIG_check__Request__bootstrap_info_t(__attribute__((__unused__)) __Request__bootstrap_info_t *In0P)
{

	typedef __Request__bootstrap_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__bootstrap_info_t__defined) */
#endif /* __MIG_check__Request__bootstrap_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine bootstrap_info */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
MIG_SERVER_ROUTINE
kern_return_t bootstrap_info
(
	mach_port_t bootstrap_port,
	name_array_t *service_names,
	mach_msg_type_number_t *service_namesCnt,
	name_array_t *server_names,
	mach_msg_type_number_t *server_namesCnt,
	bool_array_t *service_active,
	mach_msg_type_number_t *service_activeCnt
);

/* Routine bootstrap_info */
mig_internal novalue _Xbootstrap_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__bootstrap_info_t __Request;
	typedef __Reply__bootstrap_info_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__bootstrap_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__bootstrap_info_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t service_namesTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t server_namesTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t service_activeTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(408, "bootstrap_info")
	__BeforeRcvRpc(408, "bootstrap_info")

#if	defined(__MIG_check__Request__bootstrap_info_t__defined)
	check_result = __MIG_check__Request__bootstrap_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__bootstrap_info_t__defined) */

#if	UseStaticTemplates
	OutP->service_names = service_namesTemplate;
#else	/* UseStaticTemplates */
	OutP->service_names.deallocate =  TRUE;
	OutP->service_names.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->service_names.pad1 = 0;
	OutP->service_names.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->service_names.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->server_names = server_namesTemplate;
#else	/* UseStaticTemplates */
	OutP->server_names.deallocate =  TRUE;
	OutP->server_names.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->server_names.pad1 = 0;
	OutP->server_names.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->server_names.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->service_active = service_activeTemplate;
#else	/* UseStaticTemplates */
	OutP->service_active.deallocate =  TRUE;
	OutP->service_active.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->service_active.pad1 = 0;
	OutP->service_active.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->service_active.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = bootstrap_info(In0P->Head.msgh_request_port, (name_array_t *)&(OutP->service_names.address), &OutP->service_namesCnt, (name_array_t *)&(OutP->server_names.address), &OutP->server_namesCnt, (bool_array_t *)&(OutP->service_active.address), &OutP->service_activeCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->service_names.size = OutP->service_namesCnt * 128;

	OutP->server_names.size = OutP->server_namesCnt * 128;

	OutP->service_active.size = OutP->service_activeCnt * 4;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 3;
	__AfterRcvRpc(408, "bootstrap_info")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__bootstrap_subsystem__
#if !defined(__MIG_check__Request__bootstrap_subset_t__defined)
#define __MIG_check__Request__bootstrap_subset_t__defined

mig_internal kern_return_t __MIG_check__Request__bootstrap_subset_t(__attribute__((__unused__)) __Request__bootstrap_subset_t *In0P)
{

	typedef __Request__bootstrap_subset_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->requestor_port.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->requestor_port.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__bootstrap_subset_t__defined) */
#endif /* __MIG_check__Request__bootstrap_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine bootstrap_subset */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
MIG_SERVER_ROUTINE
kern_return_t bootstrap_subset
(
	mach_port_t bootstrap_port,
	mach_port_t requestor_port,
	mach_port_t *subset_port
);

/* Routine bootstrap_subset */
mig_internal novalue _Xbootstrap_subset
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t requestor_port;
		/* end of the kernel processed data */
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__bootstrap_subset_t __Request;
	typedef __Reply__bootstrap_subset_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__bootstrap_subset_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__bootstrap_subset_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t subset_portTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(409, "bootstrap_subset")
	__BeforeRcvRpc(409, "bootstrap_subset")

#if	defined(__MIG_check__Request__bootstrap_subset_t__defined)
	check_result = __MIG_check__Request__bootstrap_subset_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__bootstrap_subset_t__defined) */

#if	UseStaticTemplates
	OutP->subset_port = subset_portTemplate;
#else	/* UseStaticTemplates */
	OutP->subset_port.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->subset_port.pad1 = 0;
#endif
	OutP->subset_port.pad2 = 0;
	OutP->subset_port.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->subset_port.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = bootstrap_subset(In0P->Head.msgh_request_port, In0P->requestor_port.name, &OutP->subset_port.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(409, "bootstrap_subset")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__bootstrap_subsystem__
#if !defined(__MIG_check__Request__bootstrap_create_service_t__defined)
#define __MIG_check__Request__bootstrap_create_service_t__defined

mig_internal kern_return_t __MIG_check__Request__bootstrap_create_service_t(__attribute__((__unused__)) __Request__bootstrap_create_service_t *In0P)
{

	typedef __Request__bootstrap_create_service_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->service_name),  128);
		if (( memchr(In0P->service_name, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__bootstrap_create_service_t__defined) */
#endif /* __MIG_check__Request__bootstrap_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine bootstrap_create_service */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
MIG_SERVER_ROUTINE
kern_return_t bootstrap_create_service
(
	mach_port_t bootstrap_port,
	name_t service_name,
	mach_port_t *service_port
);

/* Routine bootstrap_create_service */
mig_internal novalue _Xbootstrap_create_service
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		name_t service_name;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__bootstrap_create_service_t __Request;
	typedef __Reply__bootstrap_create_service_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__bootstrap_create_service_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__bootstrap_create_service_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t service_portTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(410, "bootstrap_create_service")
	__BeforeRcvRpc(410, "bootstrap_create_service")

#if	defined(__MIG_check__Request__bootstrap_create_service_t__defined)
	check_result = __MIG_check__Request__bootstrap_create_service_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__bootstrap_create_service_t__defined) */

#if	UseStaticTemplates
	OutP->service_port = service_portTemplate;
#else	/* UseStaticTemplates */
	OutP->service_port.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->service_port.pad1 = 0;
#endif
	OutP->service_port.pad2 = 0;
	OutP->service_port.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->service_port.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = bootstrap_create_service(In0P->Head.msgh_request_port, In0P->service_name, &OutP->service_port.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(410, "bootstrap_create_service")
}


#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
boolean_t bootstrap_server(
		mach_msg_header_t *InHeadP,
		mach_msg_header_t *OutHeadP);

#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
mig_routine_t bootstrap_server_routine(
		mach_msg_header_t *InHeadP);


/* Description of this subsystem, for use in direct RPC */
const struct x_bootstrap_subsystem {
	mig_server_routine_t 	server;	/* Server routine */
	mach_msg_id_t	start;	/* Min routine number */
	mach_msg_id_t	end;	/* Max routine number + 1 */
	unsigned int	maxsize;	/* Max msg size */
	vm_address_t	reserved;	/* Reserved */
	struct routine_descriptor	/*Array of routine descriptors */
		routine[11];
} x_bootstrap_subsystem = {
	bootstrap_server_routine,
	400,
	411,
	(mach_msg_size_t)sizeof(union __ReplyUnion__x_bootstrap_subsystem),
	(vm_address_t)0,
	{
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xbootstrap_check_in, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__bootstrap_check_in_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xbootstrap_register, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__bootstrap_register_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xbootstrap_look_up, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__bootstrap_look_up_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xbootstrap_look_up_array, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__bootstrap_look_up_array_t)},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xbootstrap_status, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__bootstrap_status_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xbootstrap_info, 7, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__bootstrap_info_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xbootstrap_subset, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__bootstrap_subset_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xbootstrap_create_service, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__bootstrap_create_service_t)},
	}
};

mig_external boolean_t bootstrap_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 410) || (InHeadP->msgh_id < 400) ||
	    ((routine = x_bootstrap_subsystem.routine[InHeadP->msgh_id - 400].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t bootstrap_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 400;

	if ((msgh_id > 10) || (msgh_id < 0))
		return 0;

	return x_bootstrap_subsystem.routine[msgh_id].stub_routine;
}
